# Generated by Django 5.0.1 on 2024-04-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_unique_identifier_submissions_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
