# Generated by Django 5.0.1 on 2024-04-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_contact_name_contact_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='contact_images/'),
        ),
    ]
