# Generated by Django 4.2.7 on 2024-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vyas', '0002_post_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
